Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "Ubuntu-22.04"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.0.10", netmask: "255.255.255.0"

    master.vm.provider "vmware_fusion" do |vmware|
      vmware.vmx["memsize"] = "4096"
      vmware.vmx["numvcpus"] = "4"
    end
  end


  config.vm.define "worker1" do |worker|
    worker.vm.box = "Ubuntu-22.04"
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "192.168.0.11", netmask: "255.255.255.0"

    worker.vm.provider "vmware_fusion" do |vmware|
      vmware.vmx["memsize"] = "4096"
      vmware.vmx["numvcpus"] = "2"
    end
  end


  config.vm.define "worker2" do |worker|
    worker.vm.box = "Ubuntu-22.04"
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: "192.168.0.12", netmask: "255.255.255.0"

    worker.vm.provider "vmware_fusion" do |vmware|
      vmware.vmx["memsize"] = "4096"
      vmware.vmx["numvcpus"] = "2"
    end
  end
end
