apiVersion: v1
kind: Secret
metadata:
  name: myapp-db-secret
  namespace: myapp-test
type: Opaque
stringData:
  # Base64 encoding will be done automatically by K8s
  username: "myapp_test_user"
  password: "TestPassword123!"
  database: "myapp-db"
