apiVersion: v1
kind: Secret
metadata:
  name: myapp-db-secret
  namespace: myapp-staging
type: Opaque
stringData:
  # Base64 encoding will be done automatically by K8s
  username: "myapp_staging_user"
  password: "StagingPassword123!"
  database: "myapp-db"
