apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.local.server: |
    test.local:53 {
        errors
        cache 30
        forward . /etc/resolv.conf
        hosts {
            fallthrough
        }
    }
  test.local.hosts: |
    # Эти записи будут обновлены после развертывания GitLab
    # IP адреса будут указывать на Ingress или LoadBalancer
