apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.local.server: |
    test.local:53 {
        errors
        cache 30
        forward . /etc/resolv.conf
        rewrite name gitlab.test.local gitlab-webservice-default.gitlab.svc.cluster.local
        rewrite name registry.gitlab.test.local gitlab-registry.gitlab.svc.cluster.local
        rewrite name minio.gitlab.test.local gitlab-minio-svc.gitlab.svc.cluster.local
        rewrite name kas.test.local gitlab-kas.gitlab.svc.cluster.local
    }
